version: '3.4'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql.test.atdd
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT_OUT}:3306"
    volumes:
      - "../../config/mysql/conf:/etc/mysql/conf.d"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  mock-server:
    image: 'mockserver/mockserver:5.13.2'
    container_name: mock-server.test.atdd
    ports:
      - "${MOCK_SERVER_PORT_OUT}:1080"
    command: [ "-serverPort", "1080", "-logLevel", "INFO" ]
    healthcheck:
      test: [ "CMD", "nc" ,"-z", "localhost", "1080" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.test.atdd
    links:
      - mysql:db
    ports:
      - "${PHPMYADMIN_PORT_OUT}:80"

  web-driver:
    image: selenium/standalone-chrome:4.0.0-beta-3-20210426
    container_name: web-driver.test.atdd
    ports:
      - '4444:4444'
      - '7900:7900'
    extra_hosts:
      - "api.net:${HOST_NAME:-127.0.0.1}"
      - "host.docker.internal:host-gateway"
    environment:
      - VNC_NO_PASSWORD=1

  web-driver-video:
    image: josephyao/selenium-video-ffmpeg:v0.0.3
    volumes:
      - ../../videos:/videos
    ports:
      - "9000:9000"
    environment:
      - DISPLAY_CONTAINER_NAME=selenium-standalone-chrome4

  web-driver-arm:
    image: seleniarm/standalone-chromium:4.0.0-20211213
    container_name: web-driver-arm.test.atdd
    ports:
      - '4444:4444'
      - '7900:7900'
    extra_hosts:
      - "api.net:${HOST_NAME:-127.0.0.1}"
      - "host.docker.internal:host-gateway"
    environment:
      - VNC_NO_PASSWORD=1

  appium-mac:
    image: appium/appium:v1.22.3-p6
    container_name: appium.test.atdd
    privileged: true
    ports:
      - '4723:4723'
      - '8200:8200'
    volumes:
      - ../../../android/app/build/outputs/apk/debug/app-debug.apk:/tmp/app.apk
    depends_on:
      - anbox-mac

  anbox-mac:
    image: josephyao/anbox_for_docker_desktop:v4.16.2
    container_name: anbox.test.atdd
    privileged: true
    tty: true
    ports:
      - '18080:8080'
    expose:
      - 5037
    environment:
      WEBMODE: 1
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.route_localnet=1

  web:
    image: busybox:latest
    container_name: web-env-x86
    depends_on:
      - mysql
      - mock-server
      - phpmyadmin
      - web-driver
      - web-driver-video

  web-arm:
    image: busybox:latest
    container_name: web-env-arm
    depends_on:
      - mysql
      - mock-server
      - phpmyadmin
      - web-driver-arm
      - web-driver-video

  android-mac:
    image: busybox:latest
    container_name: android-env-mac
    depends_on:
      - mysql
      - mock-server
      - phpmyadmin
      - appium-mac
      - anbox-mac