variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - if [ ! -z "${CI_COMMIT_SHA}" ]; then export APP_VERSION="${CI_COMMIT_SHA:0:8}"; fi
  - if [ ! -z "${CI_COMMIT_TAG}" ]; then export APP_VERSION="${CI_COMMIT_TAG}"; fi

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test

test:
  stage: test
  image: gaoermai/docker:18.09.8-openjdk11-001
  services:
    - docker:20.10.7-dind
  script:
    - apk add --no-cache build-base nss libffi-dev openssl-dev npm
    - cd frontend && npm install && ( npm run serve & )
    - cd ..
    - IP=$(bash env/setup_docker.sh 127.0.0.1)
    - echo $IP
    - cat /etc/hosts
    - cd env && ./dc_pc up -d && cd ..
    - ./gradlew test cucumber -x npmSetup -x npmInstall -x nodeSetup -x :frontend:clean -x :frontend:npmBuild

